# Generated by Django 4.2.4 on 2025-04-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='online course', max_length=100),
        ),
    ]
